apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  annotations:
  finalizers:
  - cluster.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/cluster-name: nekropolis
  name: nekropolis
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.0.0.0/8
    services:
      cidrBlocks:
        - 172.16.0.0/12
  controlPlaneEndpoint:
    host: 192.168.10.11
    port: 6443
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: nekropolis-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: nekropolis
