apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: nekropolis-worker
spec:
  template:
    spec:
      format: cloud-config
      joinConfiguration:
        nodeRegistration:
          imagePullPolicy: IfNotPresent
          kubeletExtraArgs:
            - name: provider-id
              value: "proxmox://'{{ ds.meta_data.instance_id }}'"
      users:
        - name: root
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJeA+KvPI+y/OtbCkWpKTt9bpGKXkDtwZX3pdjzeRuRD
              Leon Welchert privat
