apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-api
resources:
- cluster.yaml
- inclusterIPpool.yaml
- kubeadmconfigtemplate-worker.yaml
- kubeadmcontrolplane.yaml
- machinedeployment-worker.yaml
- namespace.yaml
- proxmoxcluster.yaml
- proxmoxmachinetemplate-controlplane.yaml
- proxmoxmachinetemplate-worker.yaml

# these became superfluous in v1beta2
# keep them around for a bit just in case - 20250907
#patches:
#- path: patches/cluster-namespace.yaml
#- path: patches/machinedeployment-namespace.yaml
#- path: patches/kubeadmcontrolplane-namespace.yaml
#- path: patches/kubeadmcontrolplane-namespace.yaml
