apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# some of the resources have references to other resources including their namespace
# those will need to be patched
namespace: cluster-api
resources:
- cluster.yaml
- inclusterIPpool.yaml
- kubeadmconfigtemplate-worker.yaml
- kubeadmcontrolplane.yaml
- machinedeployment-worker.yaml
- namespace.yaml
- proxmoxcluster.yaml
- proxmoxmachinetemplate-controlplane.yaml
- proxmoxmachinetemplate-worker.yaml
# see note regarding namespace above
patches:
- path: patches/cluster-namespace.yaml
- path: patches/machinedeployment-namespace.yaml
- path: patches/kubeadmcontrolplane-namespace.yaml
