apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: nekropolis
  name: nekropolis-workers
spec:
  clusterName: nekropolis
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: nekropolis
      cluster.x-k8s.io/deployment-name: nekropolis-workers
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: nekropolis
        cluster.x-k8s.io/deployment-name: nekropolis-workers
        node-role.kubernetes.io/node: ''
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: nekropolis-worker
          namespace: PATCHME
      clusterName: nekropolis
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        # the german numeral suffix at the end is used to differentiate machine templates
        # within the same kubernetes release, since they should not be modified
        # see https://cluster-api.sigs.k8s.io/tasks/updating-machine-templates.html
        name: nekropolis-worker-1.31.11-drei
        namespace: PATCHME
      version: 1.31.11
