apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: nekropolis-control-plane
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 8000
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 2
      numSockets: 2
      sourceNode: pve020
      templateID: 108
