apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: nekropolis-worker
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 16000
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 4
      numSockets: 2
      sourceNode: pve002
      # this seems to be the only way to prevent VMs from being  started on
      # unsuitable Proxmox nodes
      # TODO: See if there is some other way / improve in the future when numbers of
      # physical hosts has increased
      target: pve020
      templateID: 105
